// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: grpc_server/updates/updates.proto

package updates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeUpdates_UpdateSectorOwnership_FullMethodName = "/updates.RealtimeUpdates/UpdateSectorOwnership"
)

// RealtimeUpdatesClient is the client API for RealtimeUpdates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeUpdatesClient interface {
	UpdateSectorOwnership(ctx context.Context, in *UpdateSectorOwnershipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type realtimeUpdatesClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeUpdatesClient(cc grpc.ClientConnInterface) RealtimeUpdatesClient {
	return &realtimeUpdatesClient{cc}
}

func (c *realtimeUpdatesClient) UpdateSectorOwnership(ctx context.Context, in *UpdateSectorOwnershipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RealtimeUpdates_UpdateSectorOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeUpdatesServer is the server API for RealtimeUpdates service.
// All implementations must embed UnimplementedRealtimeUpdatesServer
// for forward compatibility.
type RealtimeUpdatesServer interface {
	UpdateSectorOwnership(context.Context, *UpdateSectorOwnershipRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRealtimeUpdatesServer()
}

// UnimplementedRealtimeUpdatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeUpdatesServer struct{}

func (UnimplementedRealtimeUpdatesServer) UpdateSectorOwnership(context.Context, *UpdateSectorOwnershipRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSectorOwnership not implemented")
}
func (UnimplementedRealtimeUpdatesServer) mustEmbedUnimplementedRealtimeUpdatesServer() {}
func (UnimplementedRealtimeUpdatesServer) testEmbeddedByValue()                         {}

// UnsafeRealtimeUpdatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeUpdatesServer will
// result in compilation errors.
type UnsafeRealtimeUpdatesServer interface {
	mustEmbedUnimplementedRealtimeUpdatesServer()
}

func RegisterRealtimeUpdatesServer(s grpc.ServiceRegistrar, srv RealtimeUpdatesServer) {
	// If the following call pancis, it indicates UnimplementedRealtimeUpdatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeUpdates_ServiceDesc, srv)
}

func _RealtimeUpdates_UpdateSectorOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSectorOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeUpdatesServer).UpdateSectorOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeUpdates_UpdateSectorOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeUpdatesServer).UpdateSectorOwnership(ctx, req.(*UpdateSectorOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeUpdates_ServiceDesc is the grpc.ServiceDesc for RealtimeUpdates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeUpdates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "updates.RealtimeUpdates",
	HandlerType: (*RealtimeUpdatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSectorOwnership",
			Handler:    _RealtimeUpdates_UpdateSectorOwnership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_server/updates/updates.proto",
}
