// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: grpc_server/metadata/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        int32                  `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistanceRequest) Reset() {
	*x = GetDistanceRequest{}
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceRequest) ProtoMessage() {}

func (x *GetDistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceRequest.ProtoReflect.Descriptor instead.
func (*GetDistanceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_server_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *GetDistanceRequest) GetOrigin() int32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *GetDistanceRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type GetDistanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistanceReply) Reset() {
	*x = GetDistanceReply{}
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceReply) ProtoMessage() {}

func (x *GetDistanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceReply.ProtoReflect.Descriptor instead.
func (*GetDistanceReply) Descriptor() ([]byte, []int) {
	return file_grpc_server_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistanceReply) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type GetSectorInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sector        int32                  `protobuf:"varint,1,opt,name=sector,proto3" json:"sector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorInfoRequest) Reset() {
	*x = GetSectorInfoRequest{}
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorInfoRequest) ProtoMessage() {}

func (x *GetSectorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSectorInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_server_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *GetSectorInfoRequest) GetSector() int32 {
	if x != nil {
		return x.Sector
	}
	return 0
}

type GetSectorInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      int32                  `protobuf:"varint,1,opt,name=province,proto3" json:"province,omitempty"`
	Population    int32                  `protobuf:"varint,2,opt,name=population,proto3" json:"population,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectorInfoReply) Reset() {
	*x = GetSectorInfoReply{}
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectorInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectorInfoReply) ProtoMessage() {}

func (x *GetSectorInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectorInfoReply.ProtoReflect.Descriptor instead.
func (*GetSectorInfoReply) Descriptor() ([]byte, []int) {
	return file_grpc_server_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *GetSectorInfoReply) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *GetSectorInfoReply) GetPopulation() int32 {
	if x != nil {
		return x.Population
	}
	return 0
}

var File_grpc_server_metadata_metadata_proto protoreflect.FileDescriptor

var file_grpc_server_metadata_metadata_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x44, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x50, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xa5, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x49, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4f,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x16, 0x5a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_server_metadata_metadata_proto_rawDescOnce sync.Once
	file_grpc_server_metadata_metadata_proto_rawDescData = file_grpc_server_metadata_metadata_proto_rawDesc
)

func file_grpc_server_metadata_metadata_proto_rawDescGZIP() []byte {
	file_grpc_server_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_grpc_server_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_server_metadata_metadata_proto_rawDescData)
	})
	return file_grpc_server_metadata_metadata_proto_rawDescData
}

var file_grpc_server_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_server_metadata_metadata_proto_goTypes = []any{
	(*GetDistanceRequest)(nil),   // 0: metadata.GetDistanceRequest
	(*GetDistanceReply)(nil),     // 1: metadata.GetDistanceReply
	(*GetSectorInfoRequest)(nil), // 2: metadata.GetSectorInfoRequest
	(*GetSectorInfoReply)(nil),   // 3: metadata.GetSectorInfoReply
}
var file_grpc_server_metadata_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.MapData.GetDistance:input_type -> metadata.GetDistanceRequest
	2, // 1: metadata.MapData.GetSectorInfo:input_type -> metadata.GetSectorInfoRequest
	1, // 2: metadata.MapData.GetDistance:output_type -> metadata.GetDistanceReply
	3, // 3: metadata.MapData.GetSectorInfo:output_type -> metadata.GetSectorInfoReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_server_metadata_metadata_proto_init() }
func file_grpc_server_metadata_metadata_proto_init() {
	if File_grpc_server_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_server_metadata_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_server_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_grpc_server_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_grpc_server_metadata_metadata_proto_msgTypes,
	}.Build()
	File_grpc_server_metadata_metadata_proto = out.File
	file_grpc_server_metadata_metadata_proto_rawDesc = nil
	file_grpc_server_metadata_metadata_proto_goTypes = nil
	file_grpc_server_metadata_metadata_proto_depIdxs = nil
}
